#!/bin/sh
. scripts/_common

if [ -n "${VIRTUAL_ENV-}" ]; then
    warn 'This script should not be run inside a virtual environment.'
    exit 1
fi

if ! poetry --version | grep 1.2; then
    warn 'Poetry version 1.2 is required. This script may not function correctly.'
fi

install() {
    info 'Installing dependencies...'
    poetry install
}

install
